[workspace]
name = "data-module-template"
authors = ["See AUTHORS file"]
description = "A template for Modelblocks data modules."
license = "Apache-2.0"
readme = "README.md"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]
homepage = "https://www.modelblocks.org/"

[dependencies]
python = ">=3.12"
copier = ">=9.15.2"
mypy = ">=1.15.0"
pytest = ">=8.3.5"
ruff = ">=0.9.9"
pyyaml = ">=6.0.2"
pre-commit = ">=4.6.0"

[tasks]
test = {cmd = "pytest tests/"}
update-pre-commit = {cmd = "pre-commit autoupdate --config .pre-commit-config.yaml && pre-commit autoupdate --config template/.pre-commit-config.yaml"}
